version: "3.9"
services:
  mysql:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      # BIND-ADDRESS: 0.0.0.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default_authentication_plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      # - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/initdb/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
networks:
  default:
    driver: bridge