version: "3.9"
services:
  mysql:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    command: [
      --character-set-server=utf8mb4,
      --collation-server=utf8mb4_bin,
      --default_authentication_plugin=mysql_native_password,
      --default-time-zone=Asia/Tokyo
    ]
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/initdb/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
networks:
  default:
    driver: bridge