DROP DATABASE IF EXISTS restaurant;
DROP DATABASE IF EXISTS restaurant_test;
CREATE DATABASE restaurant;
CREATE DATABASE restaurant_test;
USE restaurant_test;

CREATE TABLE `tables` (
	`number` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`number`)
) DEFAULT CHARACTER SET=utf8mb4;

CREATE TABLE `items` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`quantity` INT UNSIGNED NOT NULL,
	`table_number` INT UNSIGNED NOT NULL,
	`start_cooking_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`finish_cooking_at` DATETIME NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
	-- FOREIGN KEY (`table_number`)
	-- 	REFERENCES `tables`(`number`)
	-- 	ON UPDATE CASCADE
) DEFAULT CHARACTER SET=utf8mb4;

USE restaurant;

CREATE TABLE `tables` (
	`number` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`number`)
) DEFAULT CHARACTER SET=utf8mb4;

CREATE TABLE `items` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`quantity` INT UNSIGNED NOT NULL,
	`table_number` INT UNSIGNED NOT NULL,
	`start_cooking_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`finish_cooking_at` DATETIME NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
	-- FOREIGN KEY (`table_number`)
	-- 	REFERENCES `tables`(`number`)
	-- 	ON UPDATE CASCADE
) DEFAULT CHARACTER SET=utf8mb4;

INSERT INTO `tables` VALUES ();
INSERT INTO `tables` VALUES ();
INSERT INTO `tables` VALUES ();
INSERT INTO `tables` VALUES ();
INSERT INTO `tables` VALUES ();

