name: Rust

on:
  push:
  pull_request:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: install Rust
      uses: actions-rs/toochain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: start up docker-compose
      run: docker-compose up -d
      
    - name: Run tests
      run: cargo test --verbose
